package ru.it_spectrum.ai.loki.mcp.model;

public enum ErrorCode {
    CONFIGURATION_ERROR, CONNECTION_REQUIRED, INVALID_CONNECTION, UNKNOWN_CONNECTION, INTERNAL_ERROR,
    INVALID_ARGUMENT, UPSTREAM_BAD_REQUEST, UPSTREAM_UNAUTHORIZED, UPSTREAM_FORBIDDEN,
    ENDPOINT_UNAVAILABLE, UPSTREAM_RATE_LIMITED, UPSTREAM_UNAVAILABLE, UPSTREAM_HTTP_ERROR,
    UPSTREAM_TIMEOUT, UPSTREAM_CONNECTION_ERROR, UPSTREAM_RESPONSE_TOO_LARGE,
    UPSTREAM_INVALID_RESPONSE, UPSTREAM_QUERY_ERROR, OPERATION_CANCELLED, RESPONSE_BUDGET_EXCEEDED
}
